// Maintainer command: write the "Playbooks for this method" block at the top of every method.
// The block is generated from the files on disk, so a new playbook is never invisible to the agent.
//   node tools/knowledge-map.mjs          rewrite the blocks
//   node tools/knowledge-map.mjs --check  exit 1 when a block is stale
import { readFileSync, readdirSync, lstatSync, writeFileSync } from 'node:fs';
import { join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classify, describe, searchKnowledge } from './brief.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const skills = join(root, 'skills');
const START = '<!-- playbooks:start (generated by tools/knowledge-map.mjs; edit the files, not this list) -->';
const END = '<!-- playbooks:end -->';
const contract = JSON.parse(readFileSync(join(skills, 'conquistador/routing-contract.json'), 'utf8'));

function files(directory, prefix = '') {
  return readdirSync(join(directory, prefix)).sort().flatMap(name => {
    const key = prefix ? `${prefix}/${name}` : name;
    const stat = lstatSync(join(directory, key));
    return stat.isDirectory() ? files(directory, key) : stat.isFile() && key.endsWith('.md') && key !== 'SKILL.md' ? [key] : [];
  });
}
const clean = text => text.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/^\[[A-Z]+\]\s*[—-]\s*/, '').replace(/^>\s*/, '').replace(/\s+/g, ' ').trim();
const clip = text => (text.length > 110 ? `${text.slice(0, 107).replace(/\s+\S*$/, '')}…` : text);
const label = key => posix.basename(key, '.md');

export function mapFor(name) {
  const directory = join(skills, name);
  const method = contract.methods[name];
  const required = new Set((method?.requiredResources ?? []).map(path => path.replace(`skills/${name}/`, '')));
  const entries = files(directory).map(key => {
    const info = describe(readFileSync(join(directory, key), 'utf8'));
    const title = clean(info.title).replace(/[.:]$/, '');
    const summary = clean(info.summary);
    return { key, kind: classify(`${name}/${key}`), summary: clip(title && !summary.startsWith(title) ? `${title}. ${summary}` : summary) };
  });
  if (!entries.length) return '';
  // Core = the method's strongest playbooks for its own purpose, plus required files and its checklist.
  const ranked = method ? searchKnowledge([method.label, method.description, ...method.intents].join(' '), { root, playbooks: [], limit: 400 })
    .filter(hit => hit.path.startsWith(`skills/${name}/`) && hit.kind === 'playbook').slice(0, 3).map(hit => hit.path.replace(`skills/${name}/`, '')) : [];
  const core = entries.filter(item => (item.kind === 'playbook' || item.kind === 'checklist') && (required.has(item.key) || ranked.includes(item.key) || item.kind === 'checklist'));
  const playbooks = entries.filter(item => item.kind === 'playbook' && !core.includes(item));
  const group = kind => entries.filter(item => item.kind === kind);
  const links = list => list.map(item => `[${label(item.key)}](${item.key})`).join(', ');
  const lines = [START, '## Playbooks for this method', ''];
  lines.push('Read the core files in full before you draft; read the others when their step or platform comes up. Cite what you used under "Playbooks applied".', '');
  if (core.length) {
    lines.push('Core:', '');
    for (const item of core) lines.push(`- [${label(item.key)}](${item.key}): ${item.summary || 'Check the draft against these before you answer.'}`);
    lines.push('');
  }
  if (playbooks.length) lines.push(`By step: ${links(playbooks)}.`, '');
  if (group('platform').length) lines.push(`Platform packs (read the one for each platform in the task): ${links(group('platform'))}.`, '');
  if (group('specialist').length) lines.push(`Specialist roles: ${links(group('specialist'))}.`, '');
  if (group('example').length) lines.push(`Worked examples: ${links(group('example'))}.`, '');
  if (group('process').length) lines.push(`Output formats and fallbacks: ${links(group('process'))}.`, '');
  lines.push(END);
  return lines.join('\n');
}

// Insert after the H1 and its first paragraph, or replace the existing block.
export function withMap(text, map) {
  const existing = text.indexOf(START);
  if (existing >= 0) {
    const end = text.indexOf(END, existing) + END.length;
    return map ? text.slice(0, existing) + map + text.slice(end) : text.slice(0, existing).replace(/\n+$/, '\n') + text.slice(end).replace(/^\n+/, '\n');
  }
  if (!map) return text;
  const h1 = text.search(/^# /m);
  const afterH1 = text.indexOf('\n\n', h1);
  const afterParagraph = text.indexOf('\n\n', afterH1 + 2);
  const at = afterParagraph < 0 ? text.length : afterParagraph;
  return `${text.slice(0, at)}\n\n${map}${text.slice(at)}`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const stale = [];
  for (const name of readdirSync(skills).sort()) {
    if (name === 'conquistador' || !lstatSync(join(skills, name)).isDirectory()) continue;
    const path = join(skills, name, 'SKILL.md');
    const text = readFileSync(path, 'utf8');
    const next = withMap(text, mapFor(name));
    if (next !== text) { stale.push(name); if (!check) writeFileSync(path, next); }
  }
  if (check && stale.length) { console.error(`Stale playbook maps: ${stale.join(', ')}. Run node tools/knowledge-map.mjs.`); process.exit(1); }
  console.log(check ? 'Playbook maps are current.' : `Updated ${stale.length} playbook maps.`);
}
