// Maintainer command: write the "Playbooks for this method" block at the top of every command,
// split mode, and play folder.
// The block is generated from the files on disk, so a new playbook is never invisible to the agent.
//   node tools/knowledge-map.mjs          rewrite the blocks
//   node tools/knowledge-map.mjs --check  exit 1 when a block is stale
import { readFileSync, readdirSync, lstatSync, writeFileSync } from 'node:fs';
import { join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { classify, describe, searchKnowledge } from './brief.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const skills = join(root, 'skills');
const parent = join(skills, 'conquistador');
const START = '<!-- playbooks:start (generated by tools/knowledge-map.mjs; edit the files, not this list) -->';
const END = '<!-- playbooks:end -->';
const contract = JSON.parse(readFileSync(join(skills, 'conquistador/routing-contract.json'), 'utf8'));

function files(directory, prefix = '') {
  return readdirSync(join(directory, prefix)).sort().filter(name => !name.startsWith('.')).flatMap(name => {
    const key = prefix ? `${prefix}/${name}` : name;
    const stat = lstatSync(join(directory, key));
    return stat.isDirectory() ? files(directory, key) : stat.isFile() && key.endsWith('.md') && key !== 'COMMAND.md' ? [key] : [];
  });
}
const exists = path => { try { return lstatSync(path).isDirectory(); } catch { return false; } };
// Modes with their own resource tree (references/modes/<mode>/) get their own map.
const splitModes = directory => exists(join(directory, 'references/modes'))
  ? readdirSync(join(directory, 'references/modes')).filter(name => name.endsWith('.md') && exists(join(directory, 'references/modes', name.slice(0, -3)))).map(name => name.slice(0, -3)) : [];

// Every document that carries a generated map: [library key prefix, map directory, document path, owner].
export function mapTargets() {
  const targets = [];
  for (const name of readdirSync(join(parent, 'commands')).sort()) {
    const directory = join(parent, 'commands', name);
    if (name.startsWith('.') || !exists(directory)) continue;
    const modes = splitModes(directory);
    targets.push({ name, directory, document: join(directory, 'COMMAND.md'), prefix: `conquistador/commands/${name}`,
      skip: key => modes.some(mode => key === `references/modes/${mode}.md` || key.startsWith(`references/modes/${mode}/`)) });
    for (const mode of modes) {
      targets.push({ name, mode, directory: join(directory, 'references/modes', mode), document: join(directory, 'references/modes', `${mode}.md`),
        prefix: `conquistador/commands/${name}/references/modes/${mode}`, linkBase: mode });
    }
  }
  for (const file of readdirSync(join(parent, 'plays')).sort()) {
    const name = file.replace(/\.md$/, '');
    if (!file.endsWith('.md') || !exists(join(parent, 'plays', name))) continue;
    targets.push({ name, play: true, directory: join(parent, 'plays', name), document: join(parent, 'plays', file), prefix: `conquistador/plays/${name}`, linkBase: name });
  }
  return targets;
}
const clean = text => text.replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/^\[[A-Z]+\]\s*[—-]\s*/, '').replace(/^>\s*/, '').replace(/\s+/g, ' ').trim();
const clip = text => (text.length > 110 ? `${text.slice(0, 107).replace(/\s+\S*$/, '')}…` : text);
const label = key => posix.basename(key, '.md');

export function mapFor(target) {
  const { name, directory, prefix, skip = () => false, linkBase } = typeof target === 'string' ? mapTargets().find(item => item.name === target && !item.mode && !item.play) : target;
  const method = target.play ? null : contract.methods[name];
  // A split mode's required files are the merged command's conditions for that mode.
  const modeRequired = target.mode ? (method?.resourceConditions ?? []).filter(item => item.when.startsWith(`Mode ${target.mode}:`)).map(item => item.path) : [];
  const required = new Set([...(method?.requiredResources ?? []), ...modeRequired].filter(path => path.startsWith(`skills/${prefix}/`)).map(path => path.slice(`skills/${prefix}/`.length)));
  const entries = files(directory).filter(key => !skip(key)).map(key => {
    const info = describe(readFileSync(join(directory, key), 'utf8'));
    const title = clean(info.title).replace(/[.:]$/, '');
    const summary = clean(info.summary);
    return { key, kind: classify(`${prefix}/${key}`), summary: clip(title && !summary.startsWith(title) ? `${title}. ${summary}` : summary) };
  });
  if (!entries.length) return '';
  // Core = the method's strongest playbooks for its own purpose, plus required files and its checklist.
  const purpose = target.play ? contract.plays.find(item => item.name === name) : method;
  const ranked = purpose ? searchKnowledge([purpose.label, purpose.description, ...purpose.intents].join(' '), { root, playbooks: [], limit: 600 })
    .filter(hit => hit.path.startsWith(`skills/${prefix}/`) && hit.kind === 'playbook').map(hit => hit.path.slice(`skills/${prefix}/`.length))
    .filter(key => !skip(key)).slice(0, 3) : [];
  const core = entries.filter(item => (item.kind === 'playbook' || item.kind === 'checklist') && (required.has(item.key) || ranked.includes(item.key) || item.kind === 'checklist'));
  const playbooks = entries.filter(item => item.kind === 'playbook' && !core.includes(item));
  const group = kind => entries.filter(item => item.kind === kind);
  const href = key => (linkBase ? `${linkBase}/${key}` : key).replace(/ /g, '%20');
  const links = list => list.map(item => `[${label(item.key)}](${href(item.key)})`).join(', ');
  const lines = [START, `## Playbooks for this ${target.play ? 'play' : target.mode ? 'mode' : 'method'}`, ''];
  lines.push('Read the core files in full before you draft; read the others when their step or platform comes up. Cite what you used under "Playbooks applied".', '');
  if (core.length) {
    lines.push('Core:', '');
    for (const item of core) lines.push(`- [${label(item.key)}](${href(item.key)}): ${item.summary || 'Check the draft against these before you answer.'}`);
    lines.push('');
  }
  if (playbooks.length) lines.push(`By step: ${links(playbooks)}.`, '');
  if (group('platform').length) lines.push(`Platform packs (read the one for each platform in the task): ${links(group('platform'))}.`, '');
  if (group('specialist').length) lines.push(`Specialist roles: ${links(group('specialist'))}.`, '');
  if (group('example').length) lines.push(`Worked examples: ${links(group('example'))}.`, '');
  if (group('process').length) lines.push(`Output formats and fallbacks: ${links(group('process'))}.`, '');
  lines.push(END);
  return lines.join('\n');
}

// Insert after the H1 and its first paragraph, or replace the existing block.
export function withMap(text, map) {
  const existing = text.indexOf(START);
  if (existing >= 0) {
    const end = text.indexOf(END, existing) + END.length;
    return map ? text.slice(0, existing) + map + text.slice(end) : text.slice(0, existing).replace(/\n+$/, '\n') + text.slice(end).replace(/^\n+/, '\n');
  }
  if (!map) return text;
  const h1 = text.search(/^# /m);
  const afterH1 = text.indexOf('\n\n', h1);
  const afterParagraph = text.indexOf('\n\n', afterH1 + 2);
  const at = afterParagraph < 0 ? text.length : afterParagraph;
  return `${text.slice(0, at)}\n\n${map}${text.slice(at)}`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const check = process.argv.includes('--check');
  const stale = [];
  for (const target of mapTargets()) {
    const text = readFileSync(target.document, 'utf8');
    const next = withMap(text, mapFor(target));
    const id = [target.name, target.mode].filter(Boolean).join(':');
    if (next !== text) { stale.push(id); if (!check) writeFileSync(target.document, next); }
  }
  if (check && stale.length) { console.error(`Stale playbook maps: ${stale.join(', ')}. Run node tools/knowledge-map.mjs.`); process.exit(1); }
  console.log(check ? 'Playbook maps are current.' : `Updated ${stale.length} playbook maps.`);
}
